### ISSUE TITLE
Sound repeats when caps lock key is held down

### ISSUE THREAD

**Issue by kotx** [AlexFlipnote/OsuKeyboard#1]
Is this intended behaviour?

**Comment by HarutoHiroki** [comment]
Holding a button down should repeat the sound until you lift your finger up

**Comment by AlexFlipnote** [comment]
Last time I checked, holding caps on OSU does in fact simulate the same experience of spamming sound.

**Comment by AlexFlipnote** [comment]
Checked with the Osu game to my PC, holding down caps lock simulated the same spam sound as you hear from this software. If anything, I could possibly just patch it to not spam with caps lock holding, just in case, we'll see what I do.
